Repository CA-G12/Bayan-Tareq-Autocomplete-proj, pull requests merged in 2022-08, with the labels that each got.

#2 1 file structure
  .eslintrc.json
  .gitignore
  index.html
  package-lock.json
  package.json
  public/page1/script.js
  public/page1/style.css
  public/page2/index.html
  public/page2/script.js
  public/page2/style.css
  src/post.json
  src/router.js
  src/server.js
Labels: approved

#5 4 create style page2
  public/page2/index.html
  public/page2/style.css
Labels: approved

#6 3 create and style home page
  index.html
  public/img/bg_home_page.jpg
  public/img/logo.png
  public/page1/style.css
Labels: approved

#10 9 change page2
  public/img/logo1.png
  public/page2/index.html
  public/page2/style.css
Labels: approved

#11 featch the api and display the results
  public/page2/dom.js
  public/page2/index.html
Labels: approved

#12 editing and styling home page
  index.html
  public/page1/style.css
Labels: awaiting-review

#13 Edit linking to css
  index.html
  public/img/home-page.png
Labels: approved

#17 creat a server
  src/server.js
Labels: awaiting-review

#18 15 router
  package-lock.json
  package.json
  src/handlers/artist.js
  src/handlers/home.js
  src/handlers/public.js
  src/router.js
Labels: approved

#19 16 json file
  src/post.json
Labels: awaiting-review

#21 add event listener on change for search input
  public/page2/dom.js
Labels: approved

#23 22 artist function
  package-lock.json
  package.json
  public/page2/dom.js
  src/handlers/artist.js
  src/handlers/home.js
  src/handlers/public.js
  src/router.js
Labels: approved

#24 Pop up function
  public/page1/script.js
  public/page2/dom.js
  public/page2/script.js
  public/page2/style.css
Labels: approved

#28 make public handler test
  package-lock.json
  package.json
  test/public.test.js
Labels: approved

#26 Creat README File
  README.md
Labels: awaiting-review

#30 make test for home handler
  src/handlers/artist.js
  test/home.test.js
Labels: approved

#31 edit port in server.js
  README.md
  src/server.js
Labels: done
